var express = require('express')
var router = express.Router()
const { authenticateToken, authorizeRole } = require('../middlewares/AuthMiddleware')

const userController = require('../controllers/UserController')

router.post('/login/facebook', userController.loginWithFirebase)
router.post('/login/google', userController.loginWithFirebase)
router.post('/login', userController.login)
router.post('/refresh-token', userController.refreshToken)
router.post('/register', userController.register)
router.get('/account/profile', authenticateToken, userController.getProfileUser)
router.put('/account/profile/edit', authenticateToken, userController.updateProfileUser)
router.post('/account/address/create', authenticateToken, userController.createAddressUser)
router.put('/account/address/update/:id', authenticateToken, userController.updateAddressUser)
router.delete('/account/address/delete/:id', authenticateToken, userController.deleteAddressUser)
router.put('/account/address/setdefault/:id', authenticateToken, userController.setDefaultAddressUser)
router.get('/account/address', authenticateToken, userController.getAddressUser)
router.get('/account/payment', authenticateToken, userController.getPaymentUser)
router.get('/account/voucher', authenticateToken, userController.getVoucherUser)
router.get('/account/favorite-products', authenticateToken, userController.getFavoriteProducts)
router.get('/purchase/order/:id', authenticateToken, userController.getOrderDetail)
router.put('/purchase/cancel/:order_id', authenticateToken, userController.cancelOrder)
router.put('/purchase/return/:order_id', authenticateToken, userController.returnOrder)
router.put('/purchase/received/:order_id', authenticateToken, userController.receivedOrder)
router.get('/purchase', authenticateToken, userController.getPurchase)
router.put('/clients/block/:userId', authenticateToken, authorizeRole(['admin']), userController.blockClient)
router.patch('/clients/block-many', authenticateToken, authorizeRole(['admin']), userController.blockManyClient)
router.put('/clients/unblock/:userId', authenticateToken, authorizeRole(['admin']), userController.unblockClient)
router.patch('/clients/unblock-many', authenticateToken, authorizeRole(['admin']), userController.unblockManyClient)
router.put('/clients/update-client-type/:userId', authenticateToken, authorizeRole(['admin']), userController.updateClientType)
router.patch('/clients/update-client-type-many', authenticateToken, authorizeRole(['admin']), userController.updateManyClientType)
router.get('/clients', authenticateToken, authorizeRole(['admin']), userController.getClients)
module.exports = router
